#!/usr/bin/env bash
set -Eeuo pipefail
umask 022

project_root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)

# Remember values explicitly supplied for this run. Existing persisted network
# settings are loaded later, but one-off environment overrides must win.
host_override_present=${AGENT_OS_HOST+x}
host_override_value=${AGENT_OS_HOST-}
port_override_present=${AGENT_OS_PORT+x}
port_override_value=${AGENT_OS_PORT-}

# shellcheck disable=SC1091
source "$project_root/config/release.env"

force_agent_web_update=0
skip_agent_web=1
skip_service=0
session_only=0
force_tls=0

usage() {
    cat <<'EOF'
Usage: ./install.sh [OPTIONS]

Options:
  --with-agent-web          Install the optional browser automation component
  --force-agent-web-update  Install/update the optional Agent Web component
  --skip-service            Install files without enabling the user service
  --session-only            Do not enable lingering; service stops after logout
  --force-tls               Replace the locally generated HTTPS certificate
  -h, --help                Show this help

The installer owns its Node.js runtime and npm dependencies. It does not use
the system Node.js, npm global prefix, or system Python packages.
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --force-agent-web-update)
            force_agent_web_update=1
            skip_agent_web=0
            ;;
        --with-agent-web)
            skip_agent_web=0
            ;;
        --skip-agent-web)
            # Backward-compatible alias; Agent Web is already opt-in.
            skip_agent_web=1
            ;;
        --skip-service)
            skip_service=1
            ;;
        --session-only)
            session_only=1
            ;;
        --force-tls)
            force_tls=1
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            usage >&2
            exit 64
            ;;
    esac
    shift
done

if [[ $EUID -eq 0 ]]; then
    echo "Run the Agent-OS installer as your normal login user, not root." >&2
    exit 77
fi

[[ $(uname -s) == Linux ]] || {
    echo "Agent-OS server installation currently supports Linux only." >&2
    exit 69
}

for required_command in bash curl install openssl sha256sum tar; do
    command -v "$required_command" >/dev/null 2>&1 || {
        echo "Missing required command: $required_command" >&2
        echo "Install the operating-system package that provides it, then retry." >&2
        exit 69
    }
done

data_root=${AGENT_OS_INSTALL_ROOT:-${XDG_DATA_HOME:-$HOME/.local/share}/agent-os}
state_root=${AGENT_OS_STATE_ROOT:-${XDG_STATE_HOME:-$HOME/.local/state}/agent-os}
config_root=${AGENT_OS_CONFIG_ROOT:-${XDG_CONFIG_HOME:-$HOME/.config}/agent-os}
bin_root=${AGENT_OS_BIN_ROOT:-$HOME/.local/bin}
runtime_root=$data_root/runtimes/node
releases_root=$data_root/releases
current_root=$data_root/current
service_dir=${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user
service_file=$service_dir/agent-os.service
runtime_config=$config_root/runtime.env

# Preserve the user's existing bind address and port across updates. Release-
# controlled values such as the server entry always come from the new release.
release_server_entry=$AGENT_OS_SERVER_ENTRY
release_bootstrap_url=$AGENT_OS_BOOTSTRAP_URL
if [[ -f "$runtime_config" ]]; then
    # runtime.env is generated by this installer and is readable only by owner.
    # shellcheck disable=SC1090
    source "$runtime_config"
    AGENT_OS_SERVER_ENTRY=$release_server_entry
    AGENT_OS_BOOTSTRAP_URL=$release_bootstrap_url
fi
if [[ -n "$host_override_present" ]]; then
    AGENT_OS_HOST=$host_override_value
fi
if [[ -n "$port_override_present" ]]; then
    AGENT_OS_PORT=$port_override_value
fi
if [[ ! "$AGENT_OS_HOST" =~ ^[A-Za-z0-9:._-]+$ ]]; then
    echo "Invalid AGENT_OS_HOST value: $AGENT_OS_HOST" >&2
    exit 64
fi
if [[ ! "$AGENT_OS_PORT" =~ ^[0-9]+$ ]] || \
   (( AGENT_OS_PORT < 1 || AGENT_OS_PORT > 65535 )); then
    echo "AGENT_OS_PORT must be an integer from 1 to 65535." >&2
    exit 64
fi

for managed_path in "$data_root" "$bin_root" "$runtime_root" "$releases_root"; do
    install -d -m 0755 "$managed_path"
done
install -d -m 0700 "$state_root" "$config_root" "$state_root/cache" "$state_root/credentials"

node_runtime=$(
    bash "$project_root/scripts/install-node-runtime.sh" \
        "$runtime_root" "$AGENT_OS_NODE_VERSION" "$AGENT_OS_NODE_DIST_URL"
)
node_binary=$node_runtime/bin/node
npm_binary=$node_runtime/bin/npm

release_id=${AGENT_OS_RELEASE_ID:-$AGENT_OS_VERSION}
release_id=${release_id//[^A-Za-z0-9._+-]/-}
release_id=${release_id#-}
release_id=${release_id%-}
[[ -n "$release_id" ]] || release_id=$AGENT_OS_VERSION
if [[ -e "$releases_root/$release_id" ]]; then
    release_id="${release_id}-$(date -u +%Y%m%d%H%M%S)"
fi
release_dir=$releases_root/$release_id
staging_dir=$(mktemp -d "$data_root/.release-${release_id}.XXXXXX")
cleanup_staging() {
    rm -rf -- "$staging_dir"
}
trap cleanup_staging EXIT

echo "Preparing Agent-OS release $release_id..."
tar -C "$project_root" \
    --exclude=.git \
    --exclude=node_modules \
    --exclude='*/node_modules' \
    --exclude='*.log' \
    -cf - . | tar -C "$staging_dir" -xf -

server_path=$staging_dir/$AGENT_OS_SERVER_ENTRY
if [[ ! -f "$server_path" || ! -d "$staging_dir/node_modules" ]]; then
    [[ -f "$staging_dir/package.json" ]] || {
        echo "Release has no prebuilt server and no package.json to build it." >&2
        echo "Expected server entry: $AGENT_OS_SERVER_ENTRY" >&2
        exit 65
    }
    [[ -x "$npm_binary" ]] || {
        echo "The managed Node.js runtime does not contain npm." >&2
        exit 70
    }

    echo "Building the release with the Agent-OS-owned Node.js runtime..."
    export PATH="$node_runtime/bin:$PATH"
    export npm_config_cache="$state_root/cache/npm"
    export npm_config_prefix="$data_root/npm-prefix"
    if [[ -n ${AGENT_OS_INSTALL_COMMAND:-} ]]; then
        (cd "$staging_dir" && bash -lc "$AGENT_OS_INSTALL_COMMAND")
    elif [[ -f "$staging_dir/package-lock.json" ]]; then
        (cd "$staging_dir" && "$npm_binary" ci)
    else
        (cd "$staging_dir" && "$npm_binary" install)
    fi

    if [[ ! -f "$server_path" ]]; then
        if [[ -n ${AGENT_OS_BUILD_COMMAND:-} ]]; then
            (cd "$staging_dir" && bash -lc "$AGENT_OS_BUILD_COMMAND")
        else
            (cd "$staging_dir" && "$npm_binary" run build)
        fi
    fi
    [[ -f "$server_path" ]] || {
        echo "Build completed without creating $AGENT_OS_SERVER_ENTRY." >&2
        exit 70
    }
    if [[ ${AGENT_OS_SKIP_NPM_PRUNE:-0} != 1 ]]; then
        (cd "$staging_dir" && "$npm_binary" prune --omit=dev)
    fi
fi

{
    printf 'RELEASE_ID=%q\n' "$release_id"
    printf 'VERSION=%q\n' "$AGENT_OS_VERSION"
    printf 'NODE_VERSION=%q\n' "$AGENT_OS_NODE_VERSION"
    printf 'INSTALLED_AT=%q\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
} >"$staging_dir/.agent-os-release"

if [[ $skip_agent_web -eq 0 ]]; then
    component_args=()
    [[ $force_agent_web_update -eq 0 ]] || component_args+=(--force-update)
    bash "$staging_dir/scripts/install-agent-web.sh" "${component_args[@]}"
else
    echo "Agent Web installation skipped; any existing installation is left untouched."
fi

mv -- "$staging_dir" "$release_dir"
trap - EXIT

previous_release=
if [[ -L "$current_root" ]]; then
    previous_release=$(readlink -f "$current_root" 2>/dev/null || true)
elif [[ -e "$current_root" ]]; then
    echo "Cannot activate release: $current_root exists and is not a symbolic link." >&2
    exit 73
fi

temporary_link=$data_root/.current.$$
ln -s "$release_dir" "$temporary_link"
mv -Tf -- "$temporary_link" "$current_root"

install -m 0755 "$release_dir/scripts/agent-osctl" "$bin_root/agent-osctl"

tls_args=("$state_root")
[[ $force_tls -eq 0 ]] || tls_args+=(--force)
bash "$release_dir/scripts/generate-tls.sh" "${tls_args[@]}" >/dev/null
tls_key_file=$state_root/tls/server.key
tls_cert_file=$state_root/tls/server.crt

{
    printf 'AGENT_OS_HOST=%q\n' "$AGENT_OS_HOST"
    printf 'AGENT_OS_PORT=%q\n' "$AGENT_OS_PORT"
    printf 'AGENT_OS_SERVER_ENTRY=%q\n' "$AGENT_OS_SERVER_ENTRY"
    printf 'AGENT_OS_BOOTSTRAP_URL=%q\n' "$AGENT_OS_BOOTSTRAP_URL"
} >"$runtime_config"
chmod 0600 "$runtime_config"

service_installed=0
if [[ $skip_service -eq 0 ]]; then
    command -v systemctl >/dev/null 2>&1 || {
        echo "systemctl is unavailable; use --skip-service for a files-only install." >&2
        exit 69
    }
    install -d -m 0755 "$service_dir"
    temporary_service=$service_dir/.agent-os.service.$$
    while IFS= read -r service_line || [[ -n "$service_line" ]]; do
        service_line=${service_line//@CURRENT_ROOT@/$current_root}
        service_line=${service_line//@DATA_ROOT@/$data_root}
        service_line=${service_line//@STATE_ROOT@/$state_root}
        service_line=${service_line//@CONFIG_ROOT@/$config_root}
        service_line=${service_line//@NODE_BINARY@/$runtime_root\/current\/bin\/node}
        service_line=${service_line//@SERVER_ENTRY@/$AGENT_OS_SERVER_ENTRY}
        service_line=${service_line//@AGENT_OS_HOST@/$AGENT_OS_HOST}
        service_line=${service_line//@AGENT_OS_PORT@/$AGENT_OS_PORT}
        service_line=${service_line//@TLS_KEY_FILE@/$tls_key_file}
        service_line=${service_line//@TLS_CERT_FILE@/$tls_cert_file}
        printf '%s\n' "$service_line"
    done <"$release_dir/systemd/agent-os.service.in" >"$temporary_service"
    install -m 0644 "$temporary_service" "$service_file"
    rm -f -- "$temporary_service"

    systemctl --user daemon-reload

    if [[ $session_only -eq 0 ]]; then
        command -v loginctl >/dev/null 2>&1 || {
            echo "loginctl is required to keep Agent-OS running after logout." >&2
            echo "Use --session-only only if stopping after logout is acceptable." >&2
            exit 69
        }
        linger_state=$(loginctl show-user "$USER" --property=Linger --value 2>/dev/null || true)
        if [[ "$linger_state" != yes ]]; then
            if loginctl enable-linger "$USER" >/dev/null 2>&1; then
                :
            elif command -v sudo >/dev/null 2>&1 && sudo loginctl enable-linger "$USER"; then
                :
            else
                echo "Agent-OS could not enable systemd user lingering." >&2
                echo "Run 'sudo loginctl enable-linger $USER', then retry." >&2
                echo "Use --session-only only if stopping after logout is acceptable." >&2
                exit 77
            fi
        fi
    fi

    if ! systemctl --user enable agent-os.service || \
       ! systemctl --user restart agent-os.service; then
        echo "Agent-OS service failed to start; restoring the previous release." >&2
        if [[ -n "$previous_release" && -d "$previous_release" ]]; then
            ln -sfn "$previous_release" "$current_root"
            systemctl --user restart agent-os.service || true
        elif [[ -L "$current_root" ]]; then
            rm -f -- "$current_root"
        fi
        exit 70
    fi
    service_installed=1

fi

echo
if [[ -n "$previous_release" ]]; then
    echo "Agent-OS updated successfully: $(basename "$previous_release") -> $release_id"
    echo "Previous release retained at: $previous_release"
else
    echo "Agent-OS $release_id installed successfully."
fi
echo "Managed Node.js: $($node_binary --version) ($node_runtime)"
if [[ $service_installed -eq 1 ]]; then
    lan_address=$(hostname -I 2>/dev/null | awk '{ print $1 }')
    lan_address=${lan_address:-127.0.0.1}
    echo "Web UI: https://${lan_address}:${AGENT_OS_PORT}"
    if [[ -s "$state_root/pairing-code" ]]; then
        echo "Pairing code: $(<"$state_root/pairing-code")"
    else
        echo "Pairing code: open the Web UI after the service finishes starting."
    fi
    certificate_fingerprint=$(openssl x509 -in "$tls_cert_file" -noout -fingerprint -sha256 \
        2>/dev/null | sed 's/^sha256 Fingerprint=//I')
    [[ -z "$certificate_fingerprint" ]] || \
        echo "TLS certificate fingerprint: $certificate_fingerprint"
fi
echo "Manage it with: $bin_root/agent-osctl status"
